AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'dayman.gemspec'

Lint/AssignmentInCondition:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Max: 15

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/Documentation:
  Enabled: false

Style/PredicateName:
  NameWhitelist:
    - 'has_one'
    - 'has_many'
