AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'dayman.gemspec'

Metrics/AbcSize:
  Max: 20

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Max: 15

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/Documentation:
  Enabled: false
